# Generated by Django 2.2 on 2021-03-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('productVendor', models.CharField(max_length=100)),
                ('addeddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviewsModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('reviews', models.CharField(max_length=400)),
                ('rating', models.IntegerField()),
                ('reviewsDate', models.DateField()),
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductsInfoModel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAvailableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecommercesite', models.CharField(max_length=100)),
                ('sellername', models.CharField(max_length=100)),
                ('sellingstartfrom', models.DateField()),
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductsInfoModel')),
            ],
        ),
    ]
